FriendsOfREDAXO/neues

README.md
Hoffe alle erwischt und wieder richtig zugeordnet zu haben :-)
=> Ein paar Links korrigiert

.gitignore, composer.json, docs/01_d_example.md, fragments/neues/entry.php, fragments/neues/list-entry.php, fragments/neues/list.php, fragments/neues/pagination.php, lang/de_de.lang, lang/en_gb.lang, lib/neues.php, lib/neues_entry.php
closes #42 Einfache Ausgabe einer Liste mit Paginierung und Detailansicht des Artikels/Posts
=> Migrationshilfe - Fragmente und Beispiel

lib/rex_api_neues_rss.php
und 
mit rex_response
sowie clear outputbuffer
=> RSS mit SimpleXML

boot.php, install.php, lib/neues.php, lib/rex_cronjob_neues_publish.php
Es werden nur noch Einträge die veröffentlicht sind ausgegeben, oder Einträge die geplant sind und deren Datum und Uhrzeit erreicht ist.
=> Nur Einträge mit Status 1 oder 0 ausgeben

install.php
Im Falle eines Updates liegen die neuen Dateien in einem Unterverzeichnis, weswegen die Generierung von
Pfadnamen wieder die bestehende Version erwischt und nicht die neue. Ich hab die Install deswegen auf __DIR__
als Ausgangspfad umgestellt. 
Update konnte ich nicht testen, aber Install lief damit durch.
=> install.php auf __DIR__ umgestellt

boot.php, install.php, lib/compatibility_classes.php, lib/neues.php, lib/neues_author.php, lib/neues_category.php, lib/neues_entry.php, lib/neues_entry_lang.php, lib/rex_api_neues_rss.php, lib/rex_cronjob_neues_publish.php, package.yml
To Do: Kompatibilitätsklassen hinterlegen, in nächster Major-Version entfernen.
=> namespace hinterlegen

boot.php, install.php, install/update_scheme.php, lib/neues.php, lib/neues_entry.php, lib/neues_restful_api.php, lib/rex_cronjob_neues_publish.php, lib/rex_cronjob_neues_sync.php
Ich hab mir erlaubt, Teile aus der `boot.php` in die Entry-Klasse zu verlagern und drum herum ein paar Kleinigkeiten zu bügeln:
- `"###neues-settings-editor###"`durch den Zielwert zu rsetzen passiert jetzt in `Entry->getForm()`
- Die Callback-Methode für den EP YFORM_DATA_LIST liegt nun in der Entry-Klasse als `Entry::epYformDataList()`
- Die Tabellennamen werden nun durch `rex::getTable()` erzeugt. Auch wenn es eh immer nur auf den Prefix rex_ hinausläuft.
- Hier erstmal prototypisch beschränkt auf `boot.php` und die Entry-Klasse:
- Table-Instanz über die Model-Class holen: `Entry::table()` statt `rex_yform_manager_table::get('rex_neues_entry')`
- Tabellennamen über die Model-Class holen: `Entry::table()->getTablename()` statt `'rex_neues_entry'`
- In der Query nicht mit einem festen …
=> Kleine Tricks in Sachen ModelClass

fragments/neues/entry.php, fragments/neues/list-entry.php, install.php, lib/Api/Rss.php, lib/Category.php, lib/Cronjob/Sync.php, lib/Entry.php, lib/EntryLang.php, lib/neues.php
Hier mal die größeren Punkte:
Entry:
- in `getCategories`:
- Rückgabetyp `null` kommt nicht vor, da `$this->getRelatedCollection` immer eine Collection liefert; entfernt
- T (=Category) ergänzt: `@return rex_yform_manager_collection<Category>`
- in `findOnline`:
- Rückgabetyp `null` kommt nicht vor, da die Quellen immer eine Collection liefern; entfernt
- T (=Entry) ergänzt: `@return rex_yform_manager_collection<Entry>`
- in `findByCategory`:
- Rückgabetyp `null` kommt nicht vor, da `$query->find()` immer eine Collection liefert; entfernt
- T (=Entry) ergänzt: `@return rex_yform_manager_collection<Entry>`
- in `findByCategoryIds`:
- Rückgabetyp `null` kommt nicht vor, da `$query->find()` immer eine Collection liefert; entfernt
- T (=Entry) ergänzt: `@return …
=> Erste Überarbeitung mit RexStan

lang/da_da.lang, lang/de_de.lang, lang/el_el.lang, lang/en_gb.lang, lang/es_es.lang, lang/fi_fi.lang, lang/fr_fr.lang, lang/it_it.lang, lang/nl_nl.lang, lang/no_no.lang, lang/pl_pl.lang, lang/ro_ro.lang, lang/sv_se.lang, lang/tr_tr.lang, lang/uk_uk.lang, lib/Api/Restful.php, lib/Api/Rss.php, lib/Cronjob/Publish.php, lib/Cronjob/Sync.php
Sync.php:
(Ja, ist noch in Arbeit.)
- nur einmal nötige Abrufe (`$this->getParam(...)`) vor die Schleife gezogen. Als Zusatznutzen meckert RexStan nicht mehr, wenn weiter unten `$status` verwendet wird ("möglicherweise nicht initialisiert") 
- Mit `REVIEW:`bzw. `FIXME:` markiert. Da stimmt was nicht. Bitte mal prüfen.
- Die .lang-Einträge sind noch unvollständig
Publish.php:
- Die zu `'neues_entry_publish_error'` und `'neues_entry_publish_success'` gehörenden .lang-Einträge werden als Template in sprintf genutzt. Der vorkommende Platzhalter `%s` ist für Strings, abr tatsächlich wird eine Zahl eingefügt; Alle .lang-Dateien geändert auf `%d`.
Restful.php:
- Die Elemente `...[get][fields] haben ja den jeweiligen Klassennamen inkl. Namespace in ausgeschriebener Form. Daher habe ich die Texte …
=> API und Cronjobs mit RexStan bearbeitet

fragments/neues/entry.php
**'Only booleans are allowed in an if condition, string given.'**
Da `$post->getPublishDate()` immer einen String liefert, besser auf "nicht `''`" abfragen.
**'Only booleans are allowed in an if condition, array|null given.'**
`$post->getImages()` liefert real immer ein Array. Somit reicht es aus, hier auf 
ein leeres Array zu prüfen. Damit das Array nicht zweimal erzeugt und abgerufen wird, dient `$images` als Zwischenspeicher.
=> RexStan-Überprüfung: fragments/neues/entry.php

lib/Api/Rss.php
RexStan-Überprüfung: **'Undefined variable: $domain'**
Das ist wohl `$domain_id` gemeint.
=> RexStan-Überprüfung: lib/Api/Rss.php

lib/Category.php
**'Public constant "FriendsOfRedaxo\Neues\Category::DRAFT" is never used'**
Na gut, `/** @pi*/`ergänzt.
**'Only booleans are allowed in an if condition, string given.'**
Da `rex_getUrl` immer eine Url erzeugt, ist die Abfrage an sich obsolet. Es wird nie auf `null` oder `''` hinauslaufen.
Daher auch Kommentare und Return-Type angepasst.
=> RexStan-Überprüfung: lib/Category.php

pages/neues.docs.php
RexStan beschwert sich über den ternären Operator (`glob(....) ?: []`): 
**'Short ternary operator is not allowed. Use null coalesce operator if applicable or consider using long ternary.'**
M.e. kann auf die Absicherung vezichtet werden, denn wenn es den Pfad nicht gibt oder für den Pfad keine Leseberechtigung vorliegt oder keine Datei dem Schema entspricht, bekommt man eh ein leeres Array. 
Um an den Pfad zu kommen, muss man sich kein Addon-Objekt holen (`rex_addon::get('neues')->getPath('docs') . '/*.md'`). Es reicht ein `rex_path::addon('neues', 'docs/*.md')`;
=> RexStan-Überprüfung: pages/neues.docs.php

uninstall.php
Für beide "Fehler" findet hier keine Korrektur statt, auch kein `ignore-next-line`; Ich habe nur Kommentare eingefügt, damit man darum weiß, da sie nicht stören und vom Code her korrekt sind. Die Fehlerkorrektur muss woanders stattfinden.
**'Unable to resolve the template type TFetchType in call to method rex_sql::getArray()'** 
**'Parameter $fetchType of method rex_sql::getArray() expects 2|3|12, 7 given.'**
Beide Meldungen kann man hier ignorieren. Das liegt an rex_sql; dort sind einige häufige PDO::FETCH_... hinterlegt,
aber eben nicht alle. In diesem Fall ist `PDO::FETCH_COLUMN` eben unbekannt. Es hat aber keinerlei funktionale
Auswirkungen.
**'Strict comparison using !== between null and Url\Profile will always evaluate to true.'**
Der Fehler hier ist ignorierbar, denn der Problembär …
=> RexStan-Überprüfung: uninstall.php

fragments/neues/list.php
**'PHPDoc tag @var for variable $posts contains generic class rex_yform_manager_collection but does not specify its types: T'**
Da fehlt die Angabe der Collection-Inhalte, also der ModelClass `Entry`: 
`/** @var rex_yform_manager_collection<Entry> $posts */`
**''Only booleans are allowed in an if condition, FriendsOfRedaxo\Neues\Entry|null given.''**
Die Fehlermeldung führt etwas in die falsche Richtung; das eigentliche Problem ist ein anderes. Hier stimmt nämlich die
Struktur nicht so ganz. 
```php
<?php foreach ($posts as $post) : ?>
<?php if($post) { ?>
<div class="col">
<?php
$fragment = new rex_fragment();
$fragment->setVar('post', $post);
echo $fragment->parse('neues/list-entry.php');
?>
</div>
<?php } else { ?>
<div class="placeholder">
<?php if(rex_config::get('neues', …
```
=> RexStan-Überprüfung: fragments/neues/list.php

lib/Cronjob/Sync.php
RexStan-Überprüfung (Level 6, REDAXO SuperGlobals|Strict-Mode|Deprecation Warnings|phpstan-dba|report mixed|dead code)
**'Property FriendsOfRedaxo\Neues\Cronjob\Sync::$counter has no type specified.'**
`/** @var ... */` hinzugefügt
**'PHPDoc tag @var for variable $response contains unknown class .....\Cronjob\rex_socket_response.'**
**'Call to method xyz() on an unknown class .....\Cronjob\rex_socket_response.'**
An zwei Stellen steht
```php
$socket = rex_socket::factoryUrl($socket_url);
/** @var rex_socket_response $response */
$response = $socket->doGet();
```
Faktisch funtioniert der Code, denn `rex_socket` ist per Use korrekt eingeordnet und `$socket->doGet()`liefert ein `\rex_socket_response`-Objekt. Somit ist der PHPDoc-Tag überflüssig. Rexstan und die IDE werten die Rückgabe auch …
=> RexStan-Überprüfung: lib/Cronjob/Sync.php

install.php, lib/Entry.php
Der Status-Code für DELETED steht z.Zt. irrtümlich auf 2 statt -2 (https://github.com/FriendsOfREDAXO/neues/pull/101#issuecomment-2334733984).
der PR fügt in die _install.php_ Code ein, der beim erstmaligen Update auf eine Version 5.1 oder größer den Wert in der Datenbank auf -2 korrigiert. Analog dazu ist Entry angepasst.
=> Umstellung Status "DELETED" von 2 auf -2

boot.php, lib/neues.php
Die von RexStan monierte Nutzung von $_REQUEST (`if(0 < count($_REQUEST))...`) ist durch die Abfrage des Console-Objektes abgelöst. Abhängig von der Frage wurde dem Addon-Titel in der Navigation ein Plus-Button angehängt.
Zu weiteren Einzelheiten des Wie und Warum siehe [hier](https://github.com/redaxo/redaxo/issues/6127#issuecomment-2354920027).
Der Code dazu wurde nach `Neues::epPagesPrepared` verlagert. Die _boot.php_ wird dadurch schlanker und übersichtlcher. Nebeneffekt: per Saldo wird weniger Code via _boot.php_ compiliert und abgearbeitet, da die meisten Seitenaufrufe i.d.R. via FE und nicht BE erfolgen.
RexStan ist einverstanden
=> $_REQUEST-Nutzung aufgelöst

lib/neues.php
Der EP PAGES_PREPARED nur angezogen wird, wenn es auch BE-Seiten gibt. In der Konsole werden keine Seiten bereitgestellt und der EP somit auch nicht aufgerufen.
Daher ist die Abfrage im EP `if (null === rex::getConsole())` faktisch redundant und kann entfernt werden.
=> Überflüssige Abfrage entfernt

lib/Cronjob/Sync.php
required-Attribut entfernen, da dies das Speichern aller Cronjobs verhindert (alle Cronjob-Formulare werden immer ausgeblendet ausgegeben)
=> Cronjob darf nicht andere Cronjobs blockieren

lib/Cronjob/Publish.php
Beim Cronjob sollte die eigentliche uhrzeit ebenfalls betrachtet werden.
=> Cronjob publish sollte ebenfalls auf die Uhrzeiten schauen. 

install/tableset.json
**Beschreibung / Description**
Die Übersetzung der Notice für die Überschrift des Titels wird nun wieder korrekt angezeigt.
Allerdings muss man `yform` und `neues` einmal re-installieren. Wobei vermutlich auch `yform` reichen würde.
=> BUGFIX: Übersetzungskey von Notice der Titel Überschrift behoben

boot.php
**Beschreibung / Description**
GitHub Issue: #135 
Ergänzt denn extension_point der mir die richtige Klasse für denn Editor an mein textarea feld class attribut dranhängt.
=> BUGFIX: OUTPUT_FILTER extension_point für editor auswahl ergänzt

lib/Author.php
**Feature / Description**
GitHub Issue: #30
Fügt eine Methode hinzu die, die `rex_neues_author` Tabelle mit den registrierten Backend Benutzern auffüllt, und diese somit als Autoren anlegt.
=> FEATURE: methode fürs auffüllen der autoren aus rex user tabelle ergänzt
